### ISSUE TITLE
Unable to import the library

### ISSUE THREAD

**Issue by madebyais** [reactivemarkets/react-financial-charts#516]
#### I'm submitting a...
- [x] bug

#### What is the current behavior
Got error when importing the lib

#### What is the expected behavior
Should be able to import the lib

#### Please tell us about your environment

From package.json
```
"dependencies": {
    "@apollo/client": "^3.2.6",
    "antd": "^4.8.0",
    "d3-scale": "^3.3.0",
    "d3-shape": "^2.1.0",
    "graphql": "^15.4.0",
    "html-react-parser": "^1.2.5",
    "jsonwebtoken": "^8.5.1",
    "next": "10.0.1",
    "nookies": "^2.5.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-financial-charts": "^1.2.2",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.2.2",
    "@storybook/addon-essentials": "^6.2.2",
    "@storybook/addon-links": "^6.2.2",
    "@storybook/react": "^6.2.2",
    "@tailwindcss/postcss7-compat": "^2.0.4",
    "@types/enzyme": "^3.10.8",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/jest": "^26.0.22",
    "@types/node": "^14.14.6",
    "@types/react": "^16.9.56",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.6.0",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-less": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "autoprefixer": "^9",
    "babel-jest": "^26.6.3",
    "enzyme": "^3.11.0",
    "esm": "^3.2.25",
    "jest": "^26.6.3",
    "less": "^3.12.2",
    "postcss": "^7",
    "postcss-preset-env": "^6.7.0",
    "sass": "^1.29.0",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
    "ts-jest": "^26.5.4",
    "typescript": "^4.1.x"
  }
```

#### Other information

```
export * from "@react-financial-charts/annotations";
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by markmcdowell** [comment]
Not a bug, please search for closed issues. This library is built using es6 so you transpile if you want to support older versions.

**Comment by rondonjon** [comment]
Just found this after opening #520. I am having the same problem, but I think this is really no transpilation problem.

I think the answer on ES6 above doesn't fully address the problem. My project imports a lot of ESM modules and transpiles them all down to ES5. For `react-financial-charts` however, the ES6 code (or the ESM exports, more specifically) are yielding errors.

This error may be caused by a misunderstanding. While it is indeed perfectly fine for modules to export their code as ES6 instead of ES5 or as ESM instead of CJS today, such modules are actually required to *indicate* that choice in their `package.json` files, which the `react-financial-charts` modules don't do.

To resolve this problem, you may want to look into the `main` and `module` attributes as described in [this LogRocket article](https://blog.logrocket.com/publishing-node-modules-typescript-es-modules/) or, if you choose to support CJS and ESM in the future, [Axel Rauschmayer's article](https://2ality.com/2019/10/hybrid-npm-packages.html) on Hybrid Packages.
